[workspace]
resolver = "2"

members = [
  "day1",
  "day2",
  "day3",
  "day4"
]

default-members = ["day4"]

[workspace.package]
version = "0.12.0"
authors = ["Spencer Dent <mr.spencerdent@gmail.com>"]
description = "Code kata advent calendar solutions for 2023"
edition = "2021"
